spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelbookingsystem
    username: postgres
    password: Kent12052@
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

app:
  admin:
    email: admin@test.com
    password: admin123
    first-name: Admin
    last-name: Root
    phone: "+70000000000"

jwt:
  secret: hbs-backend-super-secret-key-123456
  expiration-ms: 86400000
